version: '3'

services:
  airflow:
    container_name: ${NAME:-airflow}
    image: ${NAME:-airflow}:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VERSION=${VERSION:-dev}
    ports:
      - ${LOCAL_PORT:-8080}:${EXPOSE_PORT:-8080}
